### ISSUE TITLE
Cuando quiero compilarlo me bota "exited with code 9009"

### ISSUE THREAD

**Issue by ericsilvapaucar** [giansalex/homologadorSunat#3]
Me he descargado el proyecto para poder probarlo, sin embargo cuando intento correrlo usando el visual studio 2017 community, este me genera el siguiente mensaje "exited with code 9009".

**Comment by giansalex** [comment]
Hola Eric, puedes intentar depurarlo y verificar en que punto es en el que ocurre el error?

**Comment by ericsilvapaucar** [comment]
![screen shot 2018-06-28 at 10 32 22 am](https://user-images.githubusercontent.com/15257762/42044414-9377a6a8-7abe-11e8-8ffd-b6e1ea32a373.png)

En esta parte me terminan botando el error. (la pantalla fue tomado desde Mac OS X, pero el mismo error me ocurre en windows)

**Comment by giansalex** [comment]
Falto el ejecutable de [paket](https://fsprojects.github.io/Paket/getting-started.html#Manual-setup) , lo he subido al repositorio, puedes ahora actualizarlo y compilar.

**Comment by ericsilvapaucar** [comment]
Ya lo pude compilar, gracias
